#!/bin/bash
set -euo pipefail

# Signs the intermediate CA CSR with the offline root CA.
# Reads the CSR from .tmp/pki/intermediate.csr and writes the signed
# certificate to .tmp/pki/intermediate-signed.crt.
#
# Must be run from the project root directory.
#
# Required files:
#   .tmp/pki/intermediate.csr   - intermediate CSR (generated by pki:int:csr)
#   .tmp/pki/root-ca.crt        - offline root CA certificate
#   .tmp/pki/root-ca.key        - offline root CA private key

mkdir -p .tmp/pki

openssl x509 -req \
  -days 365 \
  -in .tmp/pki/intermediate.csr \
  -CA .tmp/pki/root-ca.crt \
  -CAkey .tmp/pki/root-ca.key \
  -CAcreateserial \
  -out .tmp/pki/intermediate-signed.crt \
  -extensions v3_ca \
  -extfile <(printf "[v3_ca]\nbasicConstraints=critical,CA:TRUE,pathlen:0\nkeyUsage=critical,keyCertSign,cRLSign\nsubjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid:always,issuer")

echo "Signed certificate written to .tmp/pki/intermediate-signed.crt"
