name: namespace-admin

on:
  push:
    paths:
      - 'namespace-admin/**'
  pull_request:
    paths:
      - 'namespace-admin/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  apply:
    needs: lint
    uses: ./.github/workflows/_terraform-namespace.yml
    with:
      namespace: namespace-admin
      vault_role: github-admin
    secrets: inherit
