name: namespace-tn001

on:
  push:
    paths:
      - 'namespace-tn001/**'
  pull_request:
    paths:
      - 'namespace-tn001/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  deploy:
    needs: lint
    uses: ./.github/workflows/_terraform-namespace.yml
    with:
      namespace: namespace-tn001
      vault_role: github-namespace-tn001
      vault_namespace: admin/tn001
    secrets: inherit
